service: administration-webhook

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  environment:
    JWT_SECRET: SECRET
  profile: default
  apiKeys:
    - administration-webhook-key

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: post
          private: true
