# Welcome to Serverless!
#

service: sns-message-listener

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  profile: default
  environment:
    RULES_SERVICE_URL: ${file(secret.yml):rules.url}
    RULES_SERVICE_KEY: ${file(secret.yml):rules.key}
    NOTIFICATIONS_SERVICE_URL: ${file(secret.yml):notifications.url}
    NOTIFICATIONS_SERVICE_KEY: ${file(secret.yml):notifications.key}
functions:
  dispatcher:
    handler: onMessage.onMessage
    events:
      - sns: ${file(secret.yml):sns.arn}
