service: notifications

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  environment:
    SLACK_API_TOKEN: ${file(secret.yml):secret}
  profile: default
  apiKeys:
    - notifications-service

functions:
  getChannelList:
    handler: getChannelList.getChannelList
    events:
      - http:
          path: channels
          method: get
          private: true
          request:
            parameters:
                querystring:
                    type: false
                    username: false

  sendMsg:
    handler: sendMsg.sendMsg
    events:
      - http:
          path: channels/{channel}
          method: post
          private: true
          request:
            parameters:
              paths:
                channel: true
