service: curiosity-webhook

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  environment:
    JWT_SECRET: SECRET #process.env.JWT_SECRET
    CURIOSITY_TABLE: Curiosity-${opt:stage, self:provider.stage}
  profile: default
  apiKeys:
    - curiosity-webhook-key
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CURIOSITY_TABLE}"
    

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: post
          private: true

resources:
  Resources:
    curiosityTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CURIOSITY_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1