#!/bin/sh
grunt;
grunt build-client;
echo "DEPLOY VIRTUAL ASSISTANT \n";
cd ../dist/Back-end/VirtualAssistant;
sls deploy;
echo "\n DEPLOY RULES \n";
cd ../Rules;
sls deploy;
echo "\n DEPLOY NOTIFICATIONS \n";
cd ../Notifications;
sls deploy;
echo "\n DEPLOY USERS \n";
cd ../Users;
sls deploy;
echo "\n DEPLOY EVENTS (VAMessageListener) \n";
cd ../Events;
sls deploy;
echo "\n DEPLOY CONVERSATIONS WEBHOOK \n";
cd ../ConversationWebhookService;
sls deploy;
echo "\n DEPLOY CURIOSITY WEBHOOK \n";
cd ../CuriosityWebhookService;
sls deploy;
echo "\n DEPLOY ADMINISTRATION WEBHOOK \n";
cd ../AdministrationWebhookService;
sls deploy;
echo "\n DEPLOY API GATEWAY \n";
cd ../APIGateway;
sls deploy;
