# Welcome to Serverless!
#

service: nineatavi

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  profile: default

functions:
  query:
    handler: handler.queryLambda
    events:
      - http:
          path: query
          method: post
